# Generated by Django 5.1 on 2024-08-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='done',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Done'),
        ),
    ]
