# Generated by Django 5.0.7 on 2024-08-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_tag'),
        ('todo', '0004_alter_task_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, to='master.tag'),
        ),
    ]
