# Generated by Django 5.1 on 2024-08-23 06:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_task_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='shoppinglist',
        ),
        migrations.AddField(
            model_name='task',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
