# Generated by Django 5.0.7 on 2024-08-07 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_delete_tag_alter_task_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
