# Generated by Django 5.1 on 2024-08-23 10:35

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    Task = apps.get_model("todo", "Task")
    for row in Task.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):
    dependencies = [
        ('todo', '0005_remove_task_shoppinglist_task_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
