# Generated by Django 5.1 on 2024-08-23 10:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('todo', '0006_populate_task_uuid_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
