# Generated by Django 5.0.7 on 2024-08-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_alter_product_tags'),
        ('todo', '0006_remove_task_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, to='master.tag', verbose_name='Tags'),
        ),
    ]
