# Generated by Django 5.0.7 on 2024-08-08 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_alter_item_tags_alter_list_tags'),
        ('todo', '0007_alter_task_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='shoppinglist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='shopping.list', verbose_name='Shopping list'),
        ),
    ]
