# Generated by Django 5.1 on 2024-08-23 13:23
import uuid
from django.db import migrations


def gen_uuid(apps, schema_editor):
    Product = apps.get_model("master", "Product")
    for row in Product.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):
    dependencies = [
        ('master', '0002_product_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
