# Generated by Django 5.0.7 on 2024-08-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
