# Generated by Django 5.0.7 on 2024-08-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_tag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='master.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7, verbose_name='Color'),
        ),
    ]
