# Generated by Django 5.0.7 on 2024-08-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_product_tags_alter_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='master.tag', verbose_name='Tags'),
        ),
    ]
