# Generated by Django 5.1 on 2024-08-24 14:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalDAVTasklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('etag', models.CharField(max_length=255)),
                ('sync_token', models.IntegerField(default=1)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
