# Generated by Django 5.1 on 2024-08-24 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caldav', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caldavtasklist',
            name='sync_token',
        ),
    ]
