# Generated by Django 5.1 on 2024-08-09 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductWithStock',
            fields=[
            ],
            options={
                'verbose_name': 'Product with stock',
                'verbose_name_plural': 'Products with stock',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('master.product',),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('tags', models.ManyToManyField(blank=True, to='master.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory.location', verbose_name='Location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='master.product', verbose_name='Product')),
                ('tags', models.ManyToManyField(blank=True, to='master.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Product Stock',
                'verbose_name_plural': 'Product Stock',
            },
        ),
    ]
