# Generated by Django 5.1 on 2024-08-11 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_stock', models.IntegerField(default=0, verbose_name='Minimum Stock')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.location', verbose_name='Location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='master.product', verbose_name='Product')),
                ('tags', models.ManyToManyField(blank=True, to='master.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Inventory Configuration',
                'verbose_name_plural': 'Inventory Configuration',
                'unique_together': {('product', 'location')},
            },
        ),
    ]
