# Generated by Django 5.0.7 on 2024-08-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('master', '0004_product_tags_alter_tag_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productwithstock',
            options={'verbose_name': 'Product with stock', 'verbose_name_plural': 'Products with stock'},
        ),
        migrations.AddField(
            model_name='location',
            name='tags',
            field=models.ManyToManyField(to='master.tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='productstock',
            name='tags',
            field=models.ManyToManyField(to='master.tag', verbose_name='Tags'),
        ),
    ]
