# Generated by Django 5.0.7 on 2024-08-06 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('master', '0003_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='master.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
    ]
