# Generated by Django 5.0.7 on 2024-08-06 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_location_name_alter_productstock_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstock',
            name='location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='inventory.location', verbose_name='Location'),
            preserve_default=False,
        ),
    ]
