# Generated by Django 5.1 on 2024-08-11 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_configuration'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Configuration',
            new_name='MinimumProductStock',
        ),
        migrations.AlterModelOptions(
            name='minimumproductstock',
            options={'verbose_name': 'Minimum Product Stock', 'verbose_name_plural': 'Minimum Product Stock'},
        ),
    ]
