# Generated by Django 5.0.7 on 2024-08-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_productwithstock_options_location_tags_and_more'),
        ('master', '0005_alter_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='tags',
            field=models.ManyToManyField(blank=True, to='master.tag', verbose_name='Tags'),
        ),
    ]
