# Generated by Django 5.1 on 2024-08-11 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_configuration_minimumproductstock_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='minimumproductstock',
            options={'verbose_name': 'Minimum Product Stock', 'verbose_name_plural': 'Minimum Product Stocks'},
        ),
    ]
