# Generated by Django 5.1 on 2024-08-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_minimumproductstock_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstock',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
