# Generated by Django 5.0.7 on 2024-08-06 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_productstock_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory.location', verbose_name='Location'),
        ),
    ]
