# Generated by Django 5.0.7 on 2024-08-06 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_productstock_location'),
        ('master', '0003_alter_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductWithStock',
            fields=[
            ],
            options={
                'verbose_name': ('Product with stock',),
                'verbose_name_plural': 'Products with stock',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('master.product',),
        ),
    ]
