# Generated by Django 5.1 on 2024-08-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_productstock_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstock',
            name='update_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Update reason'),
        ),
        migrations.AddField(
            model_name='productstock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
