# Generated by Django 5.1 on 2024-08-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_productstock_update_reason_productstock_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='description',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Description'),
        ),
    ]
