# Generated by Django 5.1 on 2024-08-13 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_productstock_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='minimumproductstock',
            unique_together=set(),
        ),
    ]
