# Generated by Django 5.1 on 2024-08-23 13:30
import uuid
from django.db import migrations


def gen_uuid(apps, schema_editor):
    ProductStock = apps.get_model("inventory", "ProductStock")
    for row in ProductStock.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0009_productstock_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
