# Generated by Django 5.1 on 2024-08-23 13:30
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0010_populate_productstock_uuid_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
