# Generated by Django 5.1 on 2024-08-16 18:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdav', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='collection',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='resource',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
