# Generated by Django 5.1 on 2024-08-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdav', '0002_alter_resource_collection_alter_resource_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prop',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
