# Generated by Django 5.1 on 2024-08-17 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_task_name'),
        ('webdav', '0003_alter_prop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.task'),
        ),
    ]
