# Generated by Django 5.1 on 2024-08-17 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_task_name'),
        ('webdav', '0004_resource_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.task'),
        ),
    ]
