# Generated by Django 5.1 on 2024-08-18 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_alter_item_options'),
        ('webdav', '0005_alter_resource_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='shoppingitem',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.item'),
        ),
    ]
