# Generated by Django 5.0.7 on 2024-08-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_product_tags_alter_tag_color'),
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(to='master.tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='list',
            name='tags',
            field=models.ManyToManyField(to='master.tag', verbose_name='Tags'),
        ),
    ]
