# Generated by Django 5.1 on 2024-08-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_alter_item_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='in_cart',
            field=models.BooleanField(default=False, verbose_name='In-Cart'),
        ),
    ]
