# Generated by Django 5.0.7 on 2024-08-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_alter_product_tags'),
        ('shopping', '0002_item_tags_list_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(blank=True, to='master.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='list',
            name='tags',
            field=models.ManyToManyField(blank=True, to='master.tag', verbose_name='Tags'),
        ),
    ]
