# Generated by Django 5.1 on 2024-08-12 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_item_in_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Shopping Item', 'verbose_name_plural': 'Shopping Items'},
        ),
    ]
