# Generated by Django 5.1 on 2024-08-23 07:00

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    Item = apps.get_model("shopping", "Item")
    for row in Item.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):
    dependencies = [
        ('shopping', '0005_item_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
